### ISSUE TITLE
iOS测试环境无法推送 SetApnsProduction 设置无效

### ISSUE THREAD

**Issue by AlexanderCNView** [Scorpio69t/jpush-api-golang-client#1]

**Comment by foundVanting** [comment]
![image](https://user-images.githubusercontent.com/16233666/204962673-314ec727-36c7-484e-b35a-1bab6eb29df7.png)
我也遇到了，应该是 omitempty，把false 过滤掉了

**Comment by Scorpio69t** [comment]
已解决
