### ISSUE TITLE
是否考虑加入推送短信的功能

### ISSUE THREAD

**Issue by githubhxd1995** [Scorpio69t/jpush-api-golang-client#5]
您好，我在项目的message中看到了SmsMessage是用来推送手机短信的，但是没看到实现，后续是否考虑实现一下这个功能

**Comment by Scorpio69t** [comment]
短信你得找服务商购买短信包，直接就可以发送短信，不需要走推送的通道啊，只要是发短信系统都能通知，而且短信不能随便乱发，需要有监管的

**Comment by githubhxd1995** [comment]
极光短信也支持购买短信包的，我上面的表述可能有误，参考文档在这里
https://docs.jiguang.cn/jsms/server/rest_api_jsms#api_1

**Comment by Scorpio69t** [comment]
我看到了，后续会加上的，提上日程了



---- 回复的原邮件 ----
| 发件人 | Boyce ***@***.***> |
| 日期 | 2024年04月15日 13:53 |
| 收件人 | ***@***.***> |
| 抄送至 | Mr ***@***.***>、State ***@***.***> |
| 主题 | Re: [Scorpio69t/jpush-api-golang-client] 是否考虑加入推送短信的功能 (Issue #5) |

极光短信也支持购买短信包的，我上面的表述可能有误，参考文档在这里
https://docs.jiguang.cn/jsms/server/rest_api_jsms#api_1

**Comment by githubhxd1995** [comment]
我可以提一个pr，不知道项目有没有什么规范，没看到

**Comment by Scorpio69t** [comment]
哈哈，项目也不火，还没有规范，我看看
